"""empty message

Revision ID: 348273609f25
Revises: 
Create Date: 2025-05-11 22:41:14.544584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348273609f25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carnet', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('correo', sa.String(length=200), nullable=False),
    sa.Column('contrasena', sa.String(length=200), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=80), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carnet'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('notas',
    sa.Column('id_Nota', sa.Integer(), nullable=False),
    sa.Column('id_Usuario', sa.Integer(), nullable=False),
    sa.Column('materia', sa.String(length=100), nullable=False),
    sa.Column('nota1', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('nota2', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('nota3', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_Usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_Nota')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notas')
    op.drop_table('users')
    # ### end Alembic commands ###
